name: Build Windows EXE

on:
  workflow_dispatch:
  push:

env:
  WORKDIR: .                          # change if your project is in a subfolder
  CSC_IDENTITY_AUTO_DISCOVERY: "false"  # don't attempt code signing

jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Build renderer
        run: npm run build:renderer
      - name: Build Windows app (no signing)
        run: npm run build:app
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: IdleClicker-Windows
          path: dist/*.exe
          if-no-files-found: error
